version: '3'

services:
  db:
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=changeme
    volumes:
    - pgdata:/var/lib/postgresql

  synapse:
    image: docker.io/matrixdotorg/synapse:v0.34.0-py3
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - POSTGRES_PASSWORD=changeme
    depends_on:
      - db
    ports:
      - 8008:8008

  proxy:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: sh -c 'cd /app && yarn start'
    volumes:
      - ./src:/app/src:ro
    environment:
      - DATABASE_URL=postgres://synapse:changeme@db/synapse
      - MATRIX_ENDPOINT=http://synapse:8008
    ports:
      - 4000:4000
    depends_on:
      - db
      - synapse

  minio:
    image: minio/minio
    volumes:
      - minio:/export
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: secret
      MINIO_SECRET_KEY: secretsecret
    command: server /export

  setup_minio:
    image: minio/mc
    volumes:
      - ./scripts:/scripts
    entrypoint: /scripts/wait-for-it.sh minio:9000 -- /scripts/setup-minio.sh

volumes:
  pgdata:
  minio:
